/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Card { 'photo' : ExternalBlob, 'cardNumber' : string }
export type ExternalBlob = Uint8Array;
export type IDFusionRole = { 'rto' : null } |
  { 'admin' : null } |
  { 'voter' : null } |
  { 'passport' : null } |
  { 'general' : null };
export interface Person {
  'dateOfBirth' : string,
  'passport' : [] | [Card],
  'name' : string,
  'rationCard' : [] | [Card],
  'panCard' : [] | [Card],
  'personId' : string,
  'drivingLicense' : [] | [Card],
  'voterID' : [] | [Card],
  'address' : string,
  'aadhaarCard' : [] | [Card],
  'rcCard' : [] | [Card],
}
export type PersonView = {
    'rtoView' : {
      'dateOfBirth' : string,
      'name' : string,
      'personId' : string,
      'drivingLicense' : [] | [Card],
      'address' : string,
      'rcCard' : [] | [Card],
    }
  } |
  {
    'voterView' : {
      'dateOfBirth' : string,
      'name' : string,
      'personId' : string,
      'voterID' : [] | [Card],
      'address' : string,
    }
  } |
  {
    'passportView' : {
      'dateOfBirth' : string,
      'passport' : [] | [Card],
      'name' : string,
      'personId' : string,
      'address' : string,
    }
  } |
  { 'adminView' : Person } |
  {
    'generalView' : {
      'dateOfBirth' : string,
      'name' : string,
      'rationCard' : [] | [Card],
      'panCard' : [] | [Card],
      'personId' : string,
      'address' : string,
      'aadhaarCard' : [] | [Card],
    }
  };
export interface UserProfile { 'name' : string, 'idFusionRole' : IDFusionRole }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPerson' : ActorMethod<[Person], undefined>,
  'deletePerson' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPerson' : ActorMethod<[string], PersonView>,
  'getUploadedImage' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listPersons' : ActorMethod<[], Array<Person>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPersonsByName' : ActorMethod<[string], Array<Person>>,
  'updatePerson' : ActorMethod<[string, Person], undefined>,
  'uploadImage' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];