/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Card = IDL.Record({
  'photo' : ExternalBlob,
  'cardNumber' : IDL.Text,
});
export const Person = IDL.Record({
  'dateOfBirth' : IDL.Text,
  'passport' : IDL.Opt(Card),
  'name' : IDL.Text,
  'rationCard' : IDL.Opt(Card),
  'panCard' : IDL.Opt(Card),
  'personId' : IDL.Text,
  'drivingLicense' : IDL.Opt(Card),
  'voterID' : IDL.Opt(Card),
  'address' : IDL.Text,
  'aadhaarCard' : IDL.Opt(Card),
  'rcCard' : IDL.Opt(Card),
});
export const IDFusionRole = IDL.Variant({
  'rto' : IDL.Null,
  'admin' : IDL.Null,
  'voter' : IDL.Null,
  'passport' : IDL.Null,
  'general' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'idFusionRole' : IDFusionRole,
});
export const PersonView = IDL.Variant({
  'rtoView' : IDL.Record({
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'personId' : IDL.Text,
    'drivingLicense' : IDL.Opt(Card),
    'address' : IDL.Text,
    'rcCard' : IDL.Opt(Card),
  }),
  'voterView' : IDL.Record({
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'personId' : IDL.Text,
    'voterID' : IDL.Opt(Card),
    'address' : IDL.Text,
  }),
  'passportView' : IDL.Record({
    'dateOfBirth' : IDL.Text,
    'passport' : IDL.Opt(Card),
    'name' : IDL.Text,
    'personId' : IDL.Text,
    'address' : IDL.Text,
  }),
  'adminView' : Person,
  'generalView' : IDL.Record({
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'rationCard' : IDL.Opt(Card),
    'panCard' : IDL.Opt(Card),
    'personId' : IDL.Text,
    'address' : IDL.Text,
    'aadhaarCard' : IDL.Opt(Card),
  }),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPerson' : IDL.Func([Person], [], []),
  'deletePerson' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPerson' : IDL.Func([IDL.Text], [PersonView], ['query']),
  'getUploadedImage' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPersons' : IDL.Func([], [IDL.Vec(Person)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPersonsByName' : IDL.Func([IDL.Text], [IDL.Vec(Person)], ['query']),
  'updatePerson' : IDL.Func([IDL.Text, Person], [], []),
  'uploadImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Card = IDL.Record({ 'photo' : ExternalBlob, 'cardNumber' : IDL.Text });
  const Person = IDL.Record({
    'dateOfBirth' : IDL.Text,
    'passport' : IDL.Opt(Card),
    'name' : IDL.Text,
    'rationCard' : IDL.Opt(Card),
    'panCard' : IDL.Opt(Card),
    'personId' : IDL.Text,
    'drivingLicense' : IDL.Opt(Card),
    'voterID' : IDL.Opt(Card),
    'address' : IDL.Text,
    'aadhaarCard' : IDL.Opt(Card),
    'rcCard' : IDL.Opt(Card),
  });
  const IDFusionRole = IDL.Variant({
    'rto' : IDL.Null,
    'admin' : IDL.Null,
    'voter' : IDL.Null,
    'passport' : IDL.Null,
    'general' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'idFusionRole' : IDFusionRole,
  });
  const PersonView = IDL.Variant({
    'rtoView' : IDL.Record({
      'dateOfBirth' : IDL.Text,
      'name' : IDL.Text,
      'personId' : IDL.Text,
      'drivingLicense' : IDL.Opt(Card),
      'address' : IDL.Text,
      'rcCard' : IDL.Opt(Card),
    }),
    'voterView' : IDL.Record({
      'dateOfBirth' : IDL.Text,
      'name' : IDL.Text,
      'personId' : IDL.Text,
      'voterID' : IDL.Opt(Card),
      'address' : IDL.Text,
    }),
    'passportView' : IDL.Record({
      'dateOfBirth' : IDL.Text,
      'passport' : IDL.Opt(Card),
      'name' : IDL.Text,
      'personId' : IDL.Text,
      'address' : IDL.Text,
    }),
    'adminView' : Person,
    'generalView' : IDL.Record({
      'dateOfBirth' : IDL.Text,
      'name' : IDL.Text,
      'rationCard' : IDL.Opt(Card),
      'panCard' : IDL.Opt(Card),
      'personId' : IDL.Text,
      'address' : IDL.Text,
      'aadhaarCard' : IDL.Opt(Card),
    }),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPerson' : IDL.Func([Person], [], []),
    'deletePerson' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPerson' : IDL.Func([IDL.Text], [PersonView], ['query']),
    'getUploadedImage' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPersons' : IDL.Func([], [IDL.Vec(Person)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPersonsByName' : IDL.Func([IDL.Text], [IDL.Vec(Person)], ['query']),
    'updatePerson' : IDL.Func([IDL.Text, Person], [], []),
    'uploadImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };