/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Card {
    photo: ExternalBlob;
    cardNumber: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Person {
    dateOfBirth: string;
    passport?: Card;
    name: string;
    rationCard?: Card;
    panCard?: Card;
    personId: string;
    drivingLicense?: Card;
    voterID?: Card;
    address: string;
    aadhaarCard?: Card;
    rcCard?: Card;
}
export interface UserProfile {
    name: string;
    idFusionRole: IDFusionRole;
}
export type PersonView = {
    __kind__: "rtoView";
    rtoView: {
        dateOfBirth: string;
        name: string;
        personId: string;
        drivingLicense?: Card;
        address: string;
        rcCard?: Card;
    };
} | {
    __kind__: "voterView";
    voterView: {
        dateOfBirth: string;
        name: string;
        personId: string;
        voterID?: Card;
        address: string;
    };
} | {
    __kind__: "passportView";
    passportView: {
        dateOfBirth: string;
        passport?: Card;
        name: string;
        personId: string;
        address: string;
    };
} | {
    __kind__: "adminView";
    adminView: Person;
} | {
    __kind__: "generalView";
    generalView: {
        dateOfBirth: string;
        name: string;
        rationCard?: Card;
        panCard?: Card;
        personId: string;
        address: string;
        aadhaarCard?: Card;
    };
};
export enum IDFusionRole {
    rto = "rto",
    admin = "admin",
    voter = "voter",
    passport = "passport",
    general = "general"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPerson(person: Person): Promise<void>;
    deletePerson(personId: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPerson(personId: string): Promise<PersonView>;
    getUploadedImage(key: string): Promise<ExternalBlob | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listPersons(): Promise<Array<Person>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchPersonsByName(searchTerm: string): Promise<Array<Person>>;
    updatePerson(personId: string, updatedPerson: Person): Promise<void>;
    uploadImage(key: string, blob: ExternalBlob): Promise<void>;
}
import type { Card as _Card, ExternalBlob as _ExternalBlob, IDFusionRole as _IDFusionRole, Person as _Person, PersonView as _PersonView, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPerson(arg0: Person): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPerson(await to_candid_Person_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPerson(await to_candid_Person_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deletePerson(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePerson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePerson(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerson(arg0: string): Promise<PersonView> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerson(arg0);
                return from_candid_PersonView_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerson(arg0);
            return from_candid_PersonView_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUploadedImage(arg0: string): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUploadedImage(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUploadedImage(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listPersons(): Promise<Array<Person>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPersons();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPersons();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchPersonsByName(arg0: string): Promise<Array<Person>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPersonsByName(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPersonsByName(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePerson(arg0: string, arg1: Person): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePerson(arg0, await to_candid_Person_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePerson(arg0, await to_candid_Person_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadImage(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadImage(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadImage(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_Card_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Card): Promise<Card> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_IDFusionRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IDFusionRole): IDFusionRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_PersonView_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonView): Promise<PersonView> {
    return await from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_Person_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Person): Promise<Person> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Card]): Promise<Card | null> {
    return value.length === 0 ? null : await from_candid_Card_n26(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    idFusionRole: _IDFusionRole;
}): {
    name: string;
    idFusionRole: IDFusionRole;
} {
    return {
        name: value.name,
        idFusionRole: from_candid_IDFusionRole_n18(_uploadFile, _downloadFile, value.idFusionRole)
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth: string;
    name: string;
    personId: string;
    drivingLicense: [] | [_Card];
    address: string;
    rcCard: [] | [_Card];
}): Promise<{
    dateOfBirth: string;
    name: string;
    personId: string;
    drivingLicense?: Card;
    address: string;
    rcCard?: Card;
}> {
    return {
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        personId: value.personId,
        drivingLicense: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.drivingLicense)),
        address: value.address,
        rcCard: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.rcCard))
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    photo: _ExternalBlob;
    cardNumber: string;
}): Promise<{
    photo: ExternalBlob;
    cardNumber: string;
}> {
    return {
        photo: await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.photo),
        cardNumber: value.cardNumber
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth: string;
    name: string;
    personId: string;
    voterID: [] | [_Card];
    address: string;
}): Promise<{
    dateOfBirth: string;
    name: string;
    personId: string;
    voterID?: Card;
    address: string;
}> {
    return {
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        personId: value.personId,
        voterID: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.voterID)),
        address: value.address
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth: string;
    passport: [] | [_Card];
    name: string;
    personId: string;
    address: string;
}): Promise<{
    dateOfBirth: string;
    passport?: Card;
    name: string;
    personId: string;
    address: string;
}> {
    return {
        dateOfBirth: value.dateOfBirth,
        passport: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.passport)),
        name: value.name,
        personId: value.personId,
        address: value.address
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth: string;
    passport: [] | [_Card];
    name: string;
    rationCard: [] | [_Card];
    panCard: [] | [_Card];
    personId: string;
    drivingLicense: [] | [_Card];
    voterID: [] | [_Card];
    address: string;
    aadhaarCard: [] | [_Card];
    rcCard: [] | [_Card];
}): Promise<{
    dateOfBirth: string;
    passport?: Card;
    name: string;
    rationCard?: Card;
    panCard?: Card;
    personId: string;
    drivingLicense?: Card;
    voterID?: Card;
    address: string;
    aadhaarCard?: Card;
    rcCard?: Card;
}> {
    return {
        dateOfBirth: value.dateOfBirth,
        passport: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.passport)),
        name: value.name,
        rationCard: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.rationCard)),
        panCard: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.panCard)),
        personId: value.personId,
        drivingLicense: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.drivingLicense)),
        voterID: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.voterID)),
        address: value.address,
        aadhaarCard: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.aadhaarCard)),
        rcCard: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.rcCard))
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth: string;
    name: string;
    rationCard: [] | [_Card];
    panCard: [] | [_Card];
    personId: string;
    address: string;
    aadhaarCard: [] | [_Card];
}): Promise<{
    dateOfBirth: string;
    name: string;
    rationCard?: Card;
    panCard?: Card;
    personId: string;
    address: string;
    aadhaarCard?: Card;
}> {
    return {
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        rationCard: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.rationCard)),
        panCard: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.panCard)),
        personId: value.personId,
        address: value.address,
        aadhaarCard: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.aadhaarCard))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rto: null;
} | {
    admin: null;
} | {
    voter: null;
} | {
    passport: null;
} | {
    general: null;
}): IDFusionRole {
    return "rto" in value ? IDFusionRole.rto : "admin" in value ? IDFusionRole.admin : "voter" in value ? IDFusionRole.voter : "passport" in value ? IDFusionRole.passport : "general" in value ? IDFusionRole.general : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rtoView: {
        dateOfBirth: string;
        name: string;
        personId: string;
        drivingLicense: [] | [_Card];
        address: string;
        rcCard: [] | [_Card];
    };
} | {
    voterView: {
        dateOfBirth: string;
        name: string;
        personId: string;
        voterID: [] | [_Card];
        address: string;
    };
} | {
    passportView: {
        dateOfBirth: string;
        passport: [] | [_Card];
        name: string;
        personId: string;
        address: string;
    };
} | {
    adminView: _Person;
} | {
    generalView: {
        dateOfBirth: string;
        name: string;
        rationCard: [] | [_Card];
        panCard: [] | [_Card];
        personId: string;
        address: string;
        aadhaarCard: [] | [_Card];
    };
}): Promise<{
    __kind__: "rtoView";
    rtoView: {
        dateOfBirth: string;
        name: string;
        personId: string;
        drivingLicense?: Card;
        address: string;
        rcCard?: Card;
    };
} | {
    __kind__: "voterView";
    voterView: {
        dateOfBirth: string;
        name: string;
        personId: string;
        voterID?: Card;
        address: string;
    };
} | {
    __kind__: "passportView";
    passportView: {
        dateOfBirth: string;
        passport?: Card;
        name: string;
        personId: string;
        address: string;
    };
} | {
    __kind__: "adminView";
    adminView: Person;
} | {
    __kind__: "generalView";
    generalView: {
        dateOfBirth: string;
        name: string;
        rationCard?: Card;
        panCard?: Card;
        personId: string;
        address: string;
        aadhaarCard?: Card;
    };
}> {
    return "rtoView" in value ? {
        __kind__: "rtoView",
        rtoView: await from_candid_record_n24(_uploadFile, _downloadFile, value.rtoView)
    } : "voterView" in value ? {
        __kind__: "voterView",
        voterView: await from_candid_record_n29(_uploadFile, _downloadFile, value.voterView)
    } : "passportView" in value ? {
        __kind__: "passportView",
        passportView: await from_candid_record_n30(_uploadFile, _downloadFile, value.passportView)
    } : "adminView" in value ? {
        __kind__: "adminView",
        adminView: await from_candid_Person_n31(_uploadFile, _downloadFile, value.adminView)
    } : "generalView" in value ? {
        __kind__: "generalView",
        generalView: await from_candid_record_n33(_uploadFile, _downloadFile, value.generalView)
    } : value;
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Person>): Promise<Array<Person>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Person_n31(_uploadFile, _downloadFile, x)));
}
async function to_candid_Card_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Card): Promise<_Card> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_IDFusionRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IDFusionRole): _IDFusionRole {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
async function to_candid_Person_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Person): Promise<_Person> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth: string;
    passport?: Card;
    name: string;
    rationCard?: Card;
    panCard?: Card;
    personId: string;
    drivingLicense?: Card;
    voterID?: Card;
    address: string;
    aadhaarCard?: Card;
    rcCard?: Card;
}): Promise<{
    dateOfBirth: string;
    passport: [] | [_Card];
    name: string;
    rationCard: [] | [_Card];
    panCard: [] | [_Card];
    personId: string;
    drivingLicense: [] | [_Card];
    voterID: [] | [_Card];
    address: string;
    aadhaarCard: [] | [_Card];
    rcCard: [] | [_Card];
}> {
    return {
        dateOfBirth: value.dateOfBirth,
        passport: value.passport ? candid_some(await to_candid_Card_n12(_uploadFile, _downloadFile, value.passport)) : candid_none(),
        name: value.name,
        rationCard: value.rationCard ? candid_some(await to_candid_Card_n12(_uploadFile, _downloadFile, value.rationCard)) : candid_none(),
        panCard: value.panCard ? candid_some(await to_candid_Card_n12(_uploadFile, _downloadFile, value.panCard)) : candid_none(),
        personId: value.personId,
        drivingLicense: value.drivingLicense ? candid_some(await to_candid_Card_n12(_uploadFile, _downloadFile, value.drivingLicense)) : candid_none(),
        voterID: value.voterID ? candid_some(await to_candid_Card_n12(_uploadFile, _downloadFile, value.voterID)) : candid_none(),
        address: value.address,
        aadhaarCard: value.aadhaarCard ? candid_some(await to_candid_Card_n12(_uploadFile, _downloadFile, value.aadhaarCard)) : candid_none(),
        rcCard: value.rcCard ? candid_some(await to_candid_Card_n12(_uploadFile, _downloadFile, value.rcCard)) : candid_none()
    };
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    photo: ExternalBlob;
    cardNumber: string;
}): Promise<{
    photo: _ExternalBlob;
    cardNumber: string;
}> {
    return {
        photo: await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.photo),
        cardNumber: value.cardNumber
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    idFusionRole: IDFusionRole;
}): {
    name: string;
    idFusionRole: _IDFusionRole;
} {
    return {
        name: value.name,
        idFusionRole: to_candid_IDFusionRole_n38(_uploadFile, _downloadFile, value.idFusionRole)
    };
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IDFusionRole): {
    rto: null;
} | {
    admin: null;
} | {
    voter: null;
} | {
    passport: null;
} | {
    general: null;
} {
    return value == IDFusionRole.rto ? {
        rto: null
    } : value == IDFusionRole.admin ? {
        admin: null
    } : value == IDFusionRole.voter ? {
        voter: null
    } : value == IDFusionRole.passport ? {
        passport: null
    } : value == IDFusionRole.general ? {
        general: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
